apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    provider: AWS
    resourcetype: instance
  name: ec2-aws-demo
  annotations:
     crossplane.io/paused: "false"
spec:
  forProvider:
    region: eu-west-1
    ami: ami-0d71ea30463e0ff8d
    instanceType: t2.medium
    tags:
      Name: test
      creator: aga
      managed-by: crossplane
    vpcSecurityGroupIdRefs:
      - name: securitygroup-aws-demo
    subnetIdRef:
      name: subnet-aws-demo1
  providerConfigRef:
    name: aws-config