apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: cluster-aws-demo2
  labels:
    provider: AWS
    resourcetype: cluster
  annotations:
    crossplane.io/paused: "false"
spec:
  forProvider:
    region: eu-west-1
    # roleArn: arn:aws:iam::341588796310:role/crossplane-demo
    roleArn: arn:aws:iam::741617576291:role/ohmc-cluster-9XfkneNO-cluster-20230619074319459400000003
    vpcConfig:
      - securityGroupIdRefs:
        - name: securitygroup-aws-demo
        subnetIdRefs:
          - name: subnet-aws-demo1
          - name: subnet-aws-demo2
    tags:
      Name: cluster-aws-demo
      creator: aga
      managed-by: crossplane
  writeConnectionSecretToRef:
    name: kubeconfig-eks2
    namespace: crossplane-system
  publishConnectionDetailsTo:
    name: kubeconfig-cluster-aws-demo2
    configRef:
      name: default
  providerConfigRef:
    name: aws-config
