apiVersion: ec2.aws.upbound.io/v1beta1
kind: VPC
metadata:
  name: vpc-aws-demo2
  labels:
    provider: AWS
    resourcetype: network
  annotations:
     crossplane.io/paused: "false"
spec:
  forProvider:
    region: eu-west-1
    cidrBlock: 172.0.0.0/16
    enableDnsSupport: true
    enableDnsHostnames: true
    instanceTenancy: default
    tags:
      Name: vpc-aws-demo2
      creator: aga
      managed-by: crossplane
  providerConfigRef:
    name: aws-config
